server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false
        same-site: Lax

spring:
  application:
    name: Module-Content-Tracker-RAG (railway)
#  main:
#    web-application-type: servlet
#    keep-alive: true

#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#    driver-class-name: org.postgresql.Driver


  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#springdoc:
#  api-docs:
#    enabled: false
#  #  api-docs:
##    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    with-credentials: true
springdoc:
  api-docs:
    path: v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    with-credentials: true

#    enabled: true
#    with-credentials: true
#    url: "https://module-content-tracker-backend-production.up.railway.app"

isa-modules:
  path: classpath:isa_modules/isa_modules.xlsx

security:
  admin:
    username: admin
    password: admin
  admin_import:
    username: admin_import
    password: admin_import
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 604800000  # 7 Tage
