apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    database: module-content-tracker
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
      postgresVersion: 1700
      timescaledb: false
